version: '3.8'

services:
    redis:
      image: redis:7.0.9
      command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      restart: always
      ports:
        - "6379:6379"
      volumes:
        - redis-data:/data
volumes:
  redis-data: