server:
  port: 8082

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/algafood?serverTimezone=UTC"
    username: root
    password: 1234
    hikari:
      max-lifetime: 900000

  jpa:
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false

algafood:
  jwt:
    keystore:
      path: "keystores/algafood.jks"
      password: "123456"
      keypair-alias: "algafood"